#!/usr/bin/env python3
"""Bake per-family vertical metrics from font files: Office's private DFonts
plus the standard macOS families. Word derives single spacing from
hhea asc+desc+gap (probe-verified for Arial/TNR/etc), so shipping the hhea
table for every family gives correct line pitch even when the browser
substitutes glyphs. The output maps lowercase family names to
{asc, desc, gap} in em units. Probe-calibrated
entries in measure.ts override these.

Usage: python3 scripts/extract-font-metrics.py /path/to/font-metrics.ts
"""
import struct, os, json, glob, sys

def read_tables(buf, off=0):
    n = struct.unpack_from(">H", buf, off + 4)[0]
    tabs = {}
    for i in range(n):
        tag, _, o, l = struct.unpack_from(">4sIII", buf, off + 12 + 16 * i)
        tabs[tag.decode("latin1")] = (o, l)
    return tabs

def family_name(buf, off, ln):
    cnt, strOff = struct.unpack_from(">HH", buf, off + 2)
    best = None
    for i in range(cnt):
        pid, eid, lid, nid, l, o = struct.unpack_from(">HHHHHH", buf, off + 6 + 12 * i)
        if nid != 1:
            continue
        raw = buf[off + strOff + o : off + strOff + o + l]
        if pid == 3:
            name = raw.decode("utf-16-be", "ignore")
            if lid == 0x409:
                return name
            best = best or name
        elif pid == 1 and best is None:
            best = raw.decode("mac_roman", "ignore")
    return best

def metrics_at(buf, off):
    tabs = read_tables(buf, off)
    if "head" not in tabs or "hhea" not in tabs or "name" not in tabs:
        return None
    upem = struct.unpack_from(">H", buf, tabs["head"][0] + 18)[0]
    asc, desc, gap = struct.unpack_from(">hhh", buf, tabs["hhea"][0] + 4)
    fam = family_name(buf, *tabs["name"])
    if not fam or not upem:
        return None
    return fam, {"asc": round(asc / upem, 6), "desc": round(-desc / upem, 6), "gap": round(max(gap, 0) / upem, 6)}

def scan(path, out):
    try:
        buf = open(path, "rb").read()
    except OSError:
        return
    offs = [0]
    if buf[:4] == b"ttcf":
        n = struct.unpack_from(">I", buf, 8)[0]
        offs = [struct.unpack_from(">I", buf, 12 + 4 * i)[0] for i in range(n)]
    elif buf[:4] not in (b"\x00\x01\x00\x00", b"OTTO", b"true"):
        return
    for off in offs:
        try:
            m = metrics_at(buf, off)
        except Exception:
            m = None
        if m:
            fam, met = m
            out.setdefault(fam.lower(), met)

out = {}
DIRS = [
    "/Applications/Microsoft Word.app/Contents/Resources/DFonts",
    "/System/Library/Fonts",
    "/System/Library/Fonts/Supplemental",
    "/Library/Fonts",
]
for d in DIRS:
    for f in sorted(glob.glob(os.path.join(d, "*.tt[fc]")) + glob.glob(os.path.join(d, "*.otf"))):
        scan(f, out)
if len(sys.argv) != 2:
    raise SystemExit("usage: extract-font-metrics.py OUTPUT")
dest = sys.argv[1]
lines = ["// GENERATED by scripts/extract-font-metrics.py - hhea vertical metrics",
         "// (em units) for Office DFonts + macOS system families. Word derives",
         "// single spacing from hhea asc+desc+gap; probe-calibrated entries in",
         "// measure.ts override these.",
         "export const BAKED_FONT_METRICS: Record<string, { asc: number; desc: number; gap: number }> = {"]
for k in sorted(out):
    v = out[k]
    lines.append(f'  {json.dumps(k)}: {{ asc: {v["asc"]}, desc: {v["desc"]}, gap: {v["gap"]} }},')
lines.append("};")
open(dest, "w").write("\n".join(lines) + "\n")
print("families:", len(out), "->", dest)
